model:
  name: "lightgbm"
  n_estimators: 200
  max_depth: 10
  learning_rate: 0.05
  scale_pos_weight: 500
  random_state: 42

data:
  test_size: 0.2
  random_state: 42

training:
  min_f1_score: 0.70
  min_recall: 0.70

wandb:
  project: "fraud-detection-mlops"
  entity: null